### ISSUE TITLE
Logo Design Offering as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [thindil/hunter#1]
Hello Sir. I'm an Icon and Logo Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design to improve visualization of your project as my Open Source Contribution?

Regards,

**Comment by thindil** [comment]
Dnia 2019-07-16, o godz. 05:34:48
Anhar Ismail <notifications@github.com> napisał(a):

> Hello Sir. I'm an Icon and Logo Designer. I'm happy to see an open
> source project, So, I want provide a logo for you. Would you mind if
> I propose a new logo design to improve visualization of your project
> as my Open Source Contribution?
> 
> Regards,
> 

Hello,

Thank you very much for your offer and yes I will be very happy about
this. I'm always open for propositions, especially if they are better
than my ideas. For now, as you see I'm working on my title "Worst Logo
Designer" :) Just two things:
1. Of course, because this is my free time project, I can offer in
exchange only info about your contribution in README.md file and in the
program About menu.
2. If it is possible, it will be good if license of your work will be
under license which allow to use it freely (something compatible with
GPL license). Of course, you decide what license it will be.
And that probably all from my side.

Have a nice day,
Bartek

**Comment by thindil** [comment]
I think we can close this issue due to lack of interest/answer :) If you disagree with it, feel free to reopen it.
