### ISSUE TITLE
general questions

### ISSUE THREAD

**Issue by ohenley** [thindil/hunter#4]
Hi Thindil,

This project looks awesome (exactly what I think Ada needs). I have some questions:

1) Have you considered making use of git submodule? This way we could just build it using only 2 commands (git clone --recursive ... and gprbuild ...) instead of installing every package by hand etc.

2) I did not check your architecture but I was wondering if it is ready to be ported to Windows and Mac by clearly separating an API for the file manager? This way, in due time, we could code the different platform specifics and have working ports "rapidly".

3) Is Tcl/Tk/TASHY easy sailing? Never used it (it is in my plans) yet. I say that because I just did a Github repo of the Leonid Ada port of Qt5 and it works wonder, straightforward and complete, many examples etc. I plan to add the Linux binaries soon.  

4) Is it in your plan to bundle a release.zip and distribute it on this project page?

Ok thanks and keep up the great work.

Olivier

**Comment by thindil** [comment]
Hello Ohenley :)

First, thank you very much for kind words :) Now to questions:

1. I should consider it :) I was thinking about recommending using Docker image - as is now done by Travis. But I'm open for suggestions - what will be better, to provide: full development environment in Docker or as Git submodules?
2. Hmm, at this moment it could be hard. Hunter uses for auto-updating directory listing Linux kernel `inotify` calls. If you want to do it more portable, this part of code should be separated for each system. It should be not too hard to do. About architecture - at this moment is very "solid" not portable. For example all paths are done in Unix way, there also some other calls to Unix programs (mostly related with detecting file types and highlighting). I plan to made it more portable (read: rewrite in Ada :) ) but at this moment it is not the highest priority.
3. About Tashy, I'm very biased because it is my other project :D Generally I think it is a lot better than Gtk. Much smaller, faster and offers almost (if not all) the same options like Gtk. Plus it is ported to more platforms  (for example Android also). I can't compare it to Qt because I didn't used it by very long time. But I prefer Tk a lot more that Gtk - I think it require a bit less code to write, plus looks native on all platforms. Plus you get a very nice, simple scripting language - simply perfect for creating plugins for the program :)
4. I'm distributing it as AppImage for Linux - just download, set executable permission and run :) Nothing more. If Hunter will be more portable, I will also try provide installer for Windows. Unfortunately I don't have any experience with MacOS thus I can't prepare anything for it.

Ok, I hope I answered everything, thank you again for your kind words :)

**Comment by mgrojo** [comment]
> 3. About Tashy, I'm very biased because it is my other project :D Generally I think it is a lot better than Gtk. Much smaller, faster and offers almost (if not all) the same options like Gtk. Plus it is ported to more platforms  (for example Android also). I can't compare it to Qt because I didn't used it by very long time. But I prefer Tk a lot more that Gtk - I think it require a bit less code to write, plus looks native on all platforms. Plus you get a very nice, simple scripting language - simply perfect for creating plugins for the program :)

How do you make Tk to look native in Linux platforms? The farthest I've reached is to use the 'clam' style, which doesn't look native (by that I mean that follows the current gtk theme), but at least is not so ugly. That's my critique of Tk, they've never managed to make a pleasing/modern style in Unix platforms.

**Comment by thindil** [comment]
On Linux the only possible option for now is to make own theme. In Hunter I started working on it. Some effects should be visible soon in the next development release :) As a base I use KDE Breeze theme (light and dark). Here, generally for Tk these themes: https://github.com/thindil/tkBreeze If you really want to use GTK theme I remember there was library to use GTK colors with Tk. I plan in future to add ability to use colors from GTK/Qt theme as a option.
Btw, they use default setting for Unix. Because Unix standard wasn't updated by the last 30(?) years it still require to use Motiff look and feel as default GUI :D

**Comment by mgrojo** [comment]
If you refer to these (taken from http://blog.tcl.tk/48689):

Theme | Source | Graphical? | Base | Notes | License | Author
-- | -- | -- | -- | -- | -- | --
tilegtk | external | no |   | X11 Only; out of date, could not get to compile |   |   |  
tileqt | external | no |   | X11 Only; out of date, compiles, does not work

All the references I've found said they were out of date.

Well, by "Unix" I wasn't referring to the Unix standard, but to Unix-like free-software variants. You can read that as Linux/FreeBSD. I think the Unix standard isn't relevant any more. At least, Linux distributors could make something to give a better default theme for Tk matching the default Qt/GTK themes, but they ignore Tk in general.

Your theme seems interesting. I will take a look.

**Comment by thindil** [comment]
Yes, I'm afraid I was referring to these libraries. Well, I have in my TODO list for Hunter add support for GTK colors. Tk don't have too much love because it isn't the most popular GUI library :) Except Git GUI it is hard to find any well known application written in Tk. My guess is that the most people who use/write Tk use it from Windows/MacOS.
About Unix, yes I know, but pretty often they still are called "Unixes". And still in many places they must be compatible with the old Unixes :) That's the one of problems of the Linux desktop, it don't have one official GUI API.

About themes, well, small look, not finished yet from the Hunter :)

![Screenshot_20200809_190952](https://user-images.githubusercontent.com/3816565/89737767-0c8f4980-da74-11ea-8dee-1e8e45e6577a.png)
![Screenshot_20200809_191029](https://user-images.githubusercontent.com/3816565/89737768-0d27e000-da74-11ea-87ac-740cc3252c7a.png)

**Comment by thindil** [comment]
Ok, as we have now discussions options available here, I will close this issue. Feel free to ask/request or just discuss project in Discussions :smile:
